// Generated by CoffeeScript 1.7.1
(function() {
  var BeforeUnload;

  BeforeUnload = (function() {
    function BeforeUnload() {}

    BeforeUnload.footerText = 'Are you sure you want to leave this page?';

    BeforeUnload.defaults = {
      "if": function() {
        return true;
      },
      message: 'You have unsaved changes.'
    };

    BeforeUnload.enable = function(opts) {
      opts = $.extend({}, this.defaults, opts);
      $(window).bind('beforeunload', function() {
        if (opts["if"]()) {
          return opts.message;
        } else {
          return void 0;
        }
      });
      return $(document).on('page:before-change.beforeunload', (function(_this) {
        return function(e) {
          if (!opts["if"]()) {
            return _this.disable();
          }
          if (opts.cb) {
            return opts.cb(e.originalEvent.data.url);
          } else if (confirm("" + opts.message + "\n\n" + _this.footerText)) {
            return _this.disable();
          } else {
            return false;
          }
        };
      })(this));
    };

    BeforeUnload.disable = function() {
      $(window).unbind('beforeunload');
      return $(document).off('page:before-change.beforeunload');
    };

    return BeforeUnload;

  })();

  window.BeforeUnload = BeforeUnload;

}).call(this);
